import { GoogleAuth } from 'google-auth-library';

export async function callCloudRun({
    cloudUrl,
    cloudKeyJsonString,
    path,
    method,
    body = null
}) {
    try {
        console.log("Attempting to call Cloud Run service:", cloudUrl + path);
        console.log("Using Cloud Key (first 50 chars):", cloudKeyJsonString.substring(0, 50) + '...'); // Log part of the key string

        const credentials = JSON.parse(cloudKeyJsonString);
        console.log("Credentials parsed successfully.");

        const auth = new GoogleAuth({
            credentials,
        });
        console.log("GoogleAuth client created."); 

        console.log("Getting ID token client for audience:", cloudUrl);
        const client = await auth.getIdTokenClient(cloudUrl);
        console.log("ID token client obtained."); 

        const headers = await client.getRequestHeaders();
        console.log("Request headers generated by client:", headers); 

        const fullUrl = `${cloudUrl}${path}`;

        console.log("Making fetch request to:", fullUrl);
        console.log("Fetch options:", {
            method: method,
            headers: {
                ...headers, 
                'Content-Type': 'application/json',
            },
            body: body ? '[BODY PRESENT]' : '[NO BODY]', 
        });


        const response = await fetch(fullUrl, {
            method: method,
            headers: {
                ...headers, 
                'Content-Type': 'application/json', 
            },
            body: body ? JSON.stringify(body) : undefined, 
        });

        console.log(`Workspace response received: ${response.status} ${response.statusText}`);

        if (!response.ok) {
            const errorBody = await response.text();
            console.error(`Cloud Run request failed (non-OK status): ${response.status} ${response.statusText}`, errorBody);
            throw new Error(`Cloud Run request failed: ${response.status} ${response.statusText}`);
        }
        console.log("Cloud Run request successful (OK status).");


        return response;

    } catch (error) {
        console.error('Error during callCloudRun execution:', error);
        throw error;
    }
}